const escape = (value) => value.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export function renderArchive({title,description,body,scripts='',routes,publisher,supportEmail,effectiveDate,websiteUrl,blocker}) {
  const home = title === 'Legal and safety center';
  const headings = [];
  const anchored = body.replace(/<h2>(.*?)<\/h2>/g, (_,label) => {
    const id = label.toLowerCase().replace(/<[^>]*>/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
    headings.push({id,label});
    return `<h2 id="${id}">${label}</h2>`;
  });
  const nav = routes.slice(1).map(([href,label],i)=>`<a href="${href}"><span>${String(i+1).padStart(2,'0')}</span>${label}<b aria-hidden="true">↗</b></a>`).join('');
  const content = home ? `<section class="archive-intro"><p class="coordinate">01 / THE PUBLIC RECORD</p><h2>Clarity, in writing.</h2><p>MORT is a 13+ service for local work coordination. Public visitors can learn about the mission and safety model, but jobs, participant messaging, private locations, contracts, and active-job workflows require server-approved account eligibility.</p></section><nav class="archive-index" id="documents" aria-label="Archive documents">${nav}</nav>` : `<div class="reading-layout"><aside class="contents"><p class="coordinate">IN THIS RECORD</p><nav aria-label="Document sections">${headings.map(({id,label})=>`<a href="#${id}">${label}</a>`).join('')}</nav><a class="all-records" href="/#documents">← All records</a></aside><article class="document">${anchored}</article></div>`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#090f16"><meta name="description" content="${escape(description)}"><title>${escape(title)} | MORT</title><link rel="stylesheet" href="/assets/archive.css"></head><body class="${home?'archive-home':'archive-document'}"><a class="skip" href="#content">Skip to content</a><div class="archive-world" aria-hidden="true"><div class="fallback-structure"></div><canvas id="archive-canvas"></canvas><div class="world-grain"></div></div><header class="topbar"><a class="brand" href="/">MORT <span>THE ARCHIVE</span></a><a class="back" href="https://mortapp.org">Return to MORT ↗</a></header><main id="content" tabindex="-1"><section class="archive-hero" data-scene-drag><p class="coordinate">MORT / LEGAL &amp; SAFETY / ${home?'00':'RECORD'}</p><h1>${home?'The<br><em>Archive.</em>':escape(title)}</h1><p class="hero-description">${escape(description)}</p><p class="draft">Draft — pending qualified legal review</p>${home?'<a class="enter" href="#documents">Explore the records <span aria-hidden="true">↓</span></a>':'<a class="enter" href="#reading">Read this record <span aria-hidden="true">↓</span></a>'}<p class="environment-caption" aria-hidden="true">RAIN / GLASS / THE WRITTEN RECORD<br>CHAPTER 03 — MORT</p></section><div class="reading-shell" id="reading">${blocker}<div class="notice"><strong>Current limits:</strong> MORT is a 13+ local-work coordination service with account eligibility restrictions. It does not guarantee identity, safety, jobs, or payment; it does not process real-world job payments; and identity verification is not currently available.</div>${content}</div></main><footer><a class="brand" href="/">MORT</a><p>Publisher: ${publisher} · Effective: ${effectiveDate}</p><p>Support: <a href="mailto:${supportEmail}">${supportEmail}</a> · Website: <a href="${websiteUrl}">${websiteUrl}</a></p><p>Draft — pending qualified legal review. This is public information, not legal advice.</p><nav aria-label="Footer">${routes.slice(1).map(([href,label])=>`<a href="${href}">${label}</a>`).join('')}</nav></footer><div class="scene-controls"><span aria-hidden="true">THE RAIN ROOM</span><button id="motion-toggle" type="button" aria-pressed="false">Pause atmosphere</button></div><progress id="reading-progress" max="1" value="0" aria-label="Page reading progress"></progress><script type="module" src="/assets/archive.js"></script>${scripts}</body></html>`;
}
