-- Foreign-key-side indexes identified by the Supabase Performance Advisor.

create index if not exists appearance_assignments_assigned_by_idx on public.appearance_review_assignments(assigned_by);
create index if not exists appearance_decisions_reviewer_idx on public.appearance_review_decisions(reviewer_id);
create index if not exists completion_evidence_version_idx on public.completion_evidence_records(contract_version_id);
create index if not exists completion_evidence_proof_idx on public.completion_evidence_records(proof_upload_id) where proof_upload_id is not null;
create index if not exists completion_evidence_storage_idx on public.completion_evidence_records(storage_object_id) where storage_object_id is not null;
create index if not exists completion_evidence_submitter_idx on public.completion_evidence_records(submitted_by);
create index if not exists document_capture_front_object_idx on public.document_capture_sessions(front_capture_object_id) where front_capture_object_id is not null;
create index if not exists document_capture_back_object_idx on public.document_capture_sessions(back_capture_object_id) where back_capture_object_id is not null;
create index if not exists document_web_reuse_capture_idx on public.document_web_reuse_requests(capture_session_id);
create index if not exists job_contract_acceptances_contract_idx on public.job_contract_acceptances(contract_id);
create index if not exists job_contract_change_acceptances_user_idx on public.job_contract_change_acceptances(user_id);
create index if not exists job_contract_changes_base_version_idx on public.job_contract_change_requests(base_version_id);
create index if not exists job_contract_changes_created_version_idx on public.job_contract_change_requests(created_version_id) where created_version_id is not null;
create index if not exists job_contract_changes_requester_idx on public.job_contract_change_requests(requested_by);
create index if not exists job_contract_versions_creator_idx on public.job_contract_versions(created_by) where created_by is not null;
create index if not exists job_contract_versions_source_change_idx on public.job_contract_versions(source_change_request_id) where source_change_request_id is not null;
create index if not exists job_contracts_active_version_idx on public.job_contracts(active_version_id) where active_version_id is not null;
create index if not exists job_payment_obligations_contract_idx on public.job_payment_obligations(contract_id);
create index if not exists job_payment_obligations_superseded_by_idx on public.job_payment_obligations(superseded_by_obligation_id) where superseded_by_obligation_id is not null;
create index if not exists legal_acceptance_audit_acceptance_idx on public.legal_acceptance_audit_events(acceptance_id) where acceptance_id is not null;
create index if not exists legal_acceptance_audit_decline_idx on public.legal_acceptance_audit_events(decline_id) where decline_id is not null;
create index if not exists legal_acceptance_audit_document_idx on public.legal_acceptance_audit_events(document_id);
create index if not exists legal_acceptance_audit_version_idx on public.legal_acceptance_audit_events(document_version_id);
create index if not exists legal_acceptances_document_idx on public.legal_acceptances(document_id);
create index if not exists legal_acceptances_version_idx on public.legal_acceptances(document_version_id);
create index if not exists legal_declines_document_idx on public.legal_declines(document_id);
create index if not exists legal_declines_version_idx on public.legal_declines(document_version_id);
create index if not exists legal_declines_user_idx on public.legal_declines(user_id);
create index if not exists legal_reacceptance_document_idx on public.legal_reacceptance_requirements(document_id);
create index if not exists legal_reacceptance_prior_idx on public.legal_reacceptance_requirements(prior_acceptance_id) where prior_acceptance_id is not null;
create index if not exists legal_reacceptance_required_version_idx on public.legal_reacceptance_requirements(required_version_id);
create index if not exists legal_reacceptance_satisfied_idx on public.legal_reacceptance_requirements(satisfied_by_acceptance_id) where satisfied_by_acceptance_id is not null;
create index if not exists payment_dispute_assignments_assigner_idx on public.payment_dispute_assignments(assigned_by);
create index if not exists payment_dispute_decisions_reviewer_idx on public.payment_dispute_decisions(reviewer_id);
create index if not exists payment_dispute_evidence_storage_idx on public.payment_dispute_evidence(storage_object_id) where storage_object_id is not null;
create index if not exists payment_dispute_evidence_submitter_idx on public.payment_dispute_evidence(submitted_by);
create index if not exists payment_dispute_timeline_actor_idx on public.payment_dispute_timeline(actor_id) where actor_id is not null;
create index if not exists payment_disputes_contract_idx on public.payment_disputes(contract_id);
create index if not exists payment_disputes_opener_idx on public.payment_disputes(opened_by);
create index if not exists team_access_audit_role_idx on public.team_access_audit_events(role_assignment_id) where role_assignment_id is not null;
create index if not exists team_conflict_reviewer_idx on public.team_conflict_disclosures(reviewed_by) where reviewed_by is not null;
create index if not exists team_device_reviewer_idx on public.team_device_compliance(reviewed_by) where reviewed_by is not null;
create index if not exists team_roles_approver_idx on public.team_role_assignments(approved_by) where approved_by is not null;
create index if not exists team_roles_revoker_idx on public.team_role_assignments(revoked_by) where revoked_by is not null;
create index if not exists team_role_training_module_idx on public.team_role_training_requirements(module_key);
create index if not exists team_training_approver_idx on public.team_training_completions(approved_by) where approved_by is not null;
create index if not exists team_training_module_idx on public.team_training_completions(module_key);
create index if not exists first_party_trust_enabled_by_idx on private.first_party_trust_control(enabled_by) where enabled_by is not null;
