import {KeyRing} from './key-ring.ts';
const check=(v:unknown)=>{if(!v)throw Error('Key-ring assertion failed (redacted)')};
const pair=async()=>({code:await crypto.subtle.generateKey({name:'HMAC',hash:'SHA-256'},false,['sign']),outbox:await crypto.subtle.generateKey({name:'AES-GCM',length:256},false,['encrypt','decrypt'])});
Deno.test('challengeUnderKey1RedeemsAfterKey2CurrentWithinOverlap',async()=>{let now=1_800_000_000_000;const one=await pair(),two=await pair(),old=new KeyRing({current:'k1',keys:{k1:one}},()=>now);const issued=await old.code('01234567','synthetic-item');const next=new KeyRing({current:'k2',previous:{kid:'k1',retireAt:now+1_200_000},keys:{k1:one,k2:two}},()=>now);now+=60_000;check(await next.verifyCode('01234567','synthetic-item',issued.kid,issued.digest));check(!(await next.verifyCode('01234567','different-item',issued.kid,issued.digest)))});
Deno.test('afterKey1RemovedOnlyExpiredFail',async()=>{let now=1_800_000_000_000;const one=await pair(),two=await pair(),old=new KeyRing({current:'k1',keys:{k1:one}},()=>now);const code=await old.code('01234567','synthetic-item');const rotated=new KeyRing({current:'k2',previous:{kid:'k1',retireAt:now+1_200_000},keys:{k1:one,k2:two}},()=>now);now+=1_200_000;check(!(await rotated.verifyCode('01234567','synthetic-item',code.kid,code.digest)));const removed=new KeyRing({current:'k2',keys:{k2:two}},()=>now);check(!(await removed.verifyCode('01234567','synthetic-item',code.kid,code.digest)))});
Deno.test('outboxKeyRotates',async()=>{let now=1_800_000_000_000;const one=await pair(),two=await pair(),old=new KeyRing({current:'k1',keys:{k1:one}},()=>now);const bytes=new TextEncoder().encode('synthetic-placeholder');const cipher=await old.encrypt(bytes,'context');const next=new KeyRing({current:'k2',previous:{kid:'k1',retireAt:now+1_200_000},keys:{k1:one,k2:two}},()=>now);check(new TextDecoder().decode(await next.decrypt(cipher,'context'))==='synthetic-placeholder');check((await next.encrypt(bytes,'context')).startsWith('v2.k2.'));let denied=false;try{await next.decrypt(cipher.replace('v2.k1.','v2.k2.'),'context')}catch{denied=true}check(denied)});
Deno.test('unknownKidFailsClosed',async()=>{const one=await pair(),ring=new KeyRing({current:'k1',keys:{k1:one}});const code=await ring.code('01234567','item');for(const kid of ['', 'missing', 'k1.extra'])check(!(await ring.verifyCode('01234567','item',kid,code.digest)));for(const cipher of ['v1.legacy','v2.missing.AAAA','v2..AAAA']){let denied=false;try{await ring.decrypt(cipher,'item')}catch{denied=true}check(denied)}});
Deno.test('newFlowsWorkAfterRotation',async()=>{const two=await pair(),ring=new KeyRing({current:'k2',keys:{k2:two}});const code=await ring.code('01234567','item');check(code.kid==='k2');check(await ring.verifyCode('01234567','item','k2',code.digest));check(!(await ring.verifyCode('11234567','item','k2',code.digest)))});
Deno.test('overlapCannotExceedTwentyMinutesOrChangeAtEquality',async()=>{const now=1_800_000_000_000,one=await pair(),two=await pair();let denied=false;try{new KeyRing({current:'k2',previous:{kid:'k1',retireAt:now+1_200_001},keys:{k1:one,k2:two}},()=>now)}catch{denied=true}check(denied)});

Deno.test('invalidRuntimeClockFailsClosed',async()=>{let now=1800000000000;const one=await pair(),two=await pair(),old=new KeyRing({current:'k1',keys:{k1:one}},()=>now);const code=await old.code('01234567','item');const ring=new KeyRing({current:'k2',previous:{kid:'k1',retireAt:now+1200000},keys:{k1:one,k2:two}},()=>now);now=NaN;check(!(await ring.verifyCode('01234567','item','k1',code.digest)))});
